title: WiS-CSG 2018 Survey
logo: "https://github.com/csgsciencesurvey/WISCSG2018/blob/master/images/logo_short.jpg?raw=true"
show_downloads: true
theme: jekyll-theme-minimal
blank_issues_enabled: false
